### ISSUE TITLE
Rename package and repo

### ISSUE THREAD

**Issue by maelle** [ropensci/dashboard#14]
to avoid confusion with the CRAN package `dashboard`. 😃

**Comment by jeroen** [comment]
We should have a policy against naming conflicts with CRAN packages. Installing an rOpenSci package should never overwrite a CRAN package on the user machine. Also if other packages import or depend on a package, having another package with the same name is very unfortunate.

**Comment by maelle** [comment]
Ok let me write that more explicitely under https://ropensci.github.io/dev_guide/building.html#package-name-and-metadata

**Comment by jeroen** [comment]
We should really rename this. pkgdown also assumes this is a cran pkg: https://docs.ropensci.org/dashboard/

**Comment by karthik** [comment]
Moved it to my org for now since we are not actively using this dashboard.
